# example workflow for SRM scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: Polaris-Scan
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: microsoft
          cache: maven
          
      - name: Polaris Scan
        uses: blackduck-inc/black-duck-security-scan@v2.4.0
        with:
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: 'SAST,SCA'
          polaris_test_sast_type: SAST-RAPID
          polaris_application_name: SRH-${{ github.event.repository.name }}
          polaris_project_name: hello-java
          polaris_branch_name: new
          polaris_waitforscan: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python for Polaris Branch Setter
        if: github.event_name == 'push'  # Only run on push events, not PRs
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        if: github.event_name == 'push'
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Set Polaris Default Branch
        if: github.event_name == 'push'
        env:
          POLARIS_SERVER_URL: ${{ vars.POLARIS_SERVER_URL }}
          POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          POLARIS_ORGANIZATION_ID: ${{ vars.POLARIS_ORGANIZATION_ID }}  # Optional
          POLARIS_APPLICATION_NAME: SRH-${{ github.event.repository.name }}
          POLARIS_PROJECT_NAME: hello-java
          POLARIS_BRANCH_NAME: new
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python polaris_branch_setter.py
        continue-on-error: true  # Don't fail the workflow if this step fails

      # Optional: Save logs for debugging
      # - name: Save Logs
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: bridge-logs
      #     path: ${{ github.workspace }}/.bridge
